apiVersion: v1
data:
  vhost-ssl.conf: |
    <VirtualHost *:443 *:8443>
        DocumentRoot "/var/www/eramba"
        <Directory "/var/www/eramba">
            AllowOverride all
            Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        SSLCertificateFile    /etc/ssl/certs/mycert.crt
        SSLCertificateKeyFile /etc/ssl/private/mycert.key

        LimitRequestLine 20000
    </VirtualHost>
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: eramba
  name: eramba-cm7
