apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-ssl-config
  namespace: eramba
data:
  mycert.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDozCCAougAwIBAgIUYXbflmri7zJCmrSEcb4z7qjJI0owDQYJKoZIhvcNAQEL
    BQAwejELMAkGA1UEBhMCU0sxETAPBgNVBAgMCFNsb3Zha2lhMRMwEQYDVQQHDApC
    cmF0aXNsYXZhMQ8wDQYDVQQKDAZFcmFtYmExDzANBgNVBAMMBmVyYW1iYTEhMB8G
    CSqGSIb3DQEJARYSc3VwcG9ydEBlcmFtYmEub3JnMB4XDTI0MTAwNzEyMDEyOVoX
    DTI1MTAwNzEyMDEyOVowejELMAkGA1UEBhMCU0sxETAPBgNVBAgMCFNsb3Zha2lh
    MRMwEQYDVQQHDApCcmF0aXNsYXZhMQ8wDQYDVQQKDAZFcmFtYmExDzANBgNVBAMM
    BmVyYW1iYTEhMB8GCSqGSIb3DQEJARYSc3VwcG9ydEBlcmFtYmEub3JnMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1O1lcf5xYhPU6YgxYpUPyWpvHm7q
    J3jRWbced5JHkG+Nj3qVAuLmxGXG+EGsjyoyEGHFU/LfHecn9fcdg/O3iFyaozsz
    xMLqtJxUs3ulhfAgxJeFtxktvXgfvhRCR0EmG3mLN7mILU5jjY06CdijS5rHDIBt
    wamnb+2wcq/LoufJpWIS/1rE0pTgHuOEuY4QnHJRXgMj1SPLzZv/bDH+4JybvIlf
    R5H9rmAFuLdQHZ5Pl9i3WbasFVqOBnBMZrUn872BVfNzH5h0oYIf5lqERDOtSTKM
    uMWdziqoxS0sj9ffzzj9nMeW0e6iVFC4LtpthCGT16/B+SF8MPzlGPagdQIDAQAB
    oyEwHzAdBgNVHQ4EFgQUy5B8b6D/KYsUogz654Th4OLySYMwDQYJKoZIhvcNAQEL
    BQADggEBABDttCU1Ze01MNd3iRlRfwh96bpNLFd2Jy/sRjC7tlP5n+fTEo62TBnZ
    0cbx2S0VVZZYmk3dgD8yVUioGozdKLKItaUyn+/+36/vXREVYhqFYXJcinb8CwvF
    yxQ9GQA9fTsMajziV41YE8JCdSDG1bJ9VhyukVC9tbGbHv9tL64a85jrjnW8WeCe
    Nck8w6XyE9bxKjOX97j/ydDwp3J7Dss2pQWVjsf7eJNxnQhh5i5zVfd8dAkYfVjg
    ihB9BPPyhV3fsQYFXeXvTdz6JcTpTN/ub8DyPC2PCXrSYHte4QyYaZuqsJKzE+8N
    MSLtnvL9nzDO1HFOLMxxMEM0WFEQtgw=
    -----END CERTIFICATE-----
  mycert.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDU7WVx/nFiE9Tp
    iDFilQ/Jam8ebuoneNFZtx53kkeQb42PepUC4ubEZcb4QayPKjIQYcVT8t8d5yf1
    9x2D87eIXJqjOzPEwuq0nFSze6WF8CDEl4W3GS29eB++FEJHQSYbeYs3uYgtTmON
    jToJ2KNLmscMgG3Bqadv7bByr8ui58mlYhL/WsTSlOAe44S5jhCcclFeAyPVI8vN
    m/9sMf7gnJu8iV9Hkf2uYAW4t1Adnk+X2LdZtqwVWo4GcExmtSfzvYFV83MfmHSh
    gh/mWoREM61JMoy4xZ3OKqjFLSyP19/POP2cx5bR7qJUULgu2m2EIZPXr8H5IXww
    /OUY9qB1AgMBAAECggEAE/fXZaNY+rulYek1yGr2OgtTNGVubBk2eNVldA0xzOfJ
    PMVgKA8jWRO6Xxm5lwt7+nFQ0hiat/EvnC96gx9d/NnCXsB0kGU/IYTvpI1Z7n+g
    cw9KqOshkP0s7OR1er0vV7BEUAuEK8uIJoQyBy5b0gFH3XJF2L2SSDrgK0E1Naef
    IwgvgsaOHNMRC1xtLVa2CRocZJy0crkl5H0uHnMff261HD7332C2lursPkbMbgJ8
    W5N12E8kqXA2lPqpmr8BWMrfeqfHm9nQ8ey/TPMHeetmh2G2quzdR+LVxPsgWHds
    htuh3rzaxDfSS7iqr+DYprsCh2rF6fJyop5kyTdqQQKBgQD8aCIM2NaVRdWbUBML
    H41q9yUVTT1/Xd2zK6bcxbHtlQvAQrN8CgjJwkbN3HPQihthugJv9IMIjwpufGES
    vkZS3iUL59mDeR4NmkwJk3dL/uZa3FaqJM3rva/cz+QB6Iqd5c3yUrKgkV/IqFD/
    XnVJqslpTBkR/PCYFtS0fDLHXQKBgQDX9WKS0IqliYhKycE1IjZ9Kqs5npjHj8hc
    itZJZzgX2m1t+Mp4QsKE0/XDw8/BsAweg8pj5UkXYR84uz3aNrHOgveqmV48eVmh
    RR7ghUYrfD9kIwoeMtoc/5BN1xd1+rNuzVZalNxVl9ajirg6anKdE8GUU41349m6
    fOpRc4Uj+QKBgQCRqJZdy5SpuA84/dC/jonRvKYN0PE4WzbhesNkjEHN1UFexh9F
    6ZSAujiZ/CppogmDMBDQAs7LVaCzedubMWrrz36ZjEad9Hs/ZleS/yLNHGBa9uSc
    c3jSHjkquF3gLA4yaLecq9ShjMM1zMxRUnVk+cYZmeyt0MYXPrWpIjM7kQKBgQCz
    vn57+ezcGNuCe+g+pCo8BY6cF5/LwaWfOMNgNvQeDmQ0OvWyIMasLYsJlGnQKQn9
    P+3tNUKfneuRmW7Ct/FIFAO1T496v/nU26X2c5bSzMgqPWvHdMXLiv59e0AAp1g/
    KdLs86dr6kPwvJ3XqQ+aI35kSSKfHdrzd9LDVmYDaQKBgErmrEx+z4alXcIJDA4q
    H4H6X1G3r56hwrfpRNWbKE/bVot2vhnN/LlbyOSRgrhXwKjnb2FRKvkeV3I3FBbB
    qt8gCe0Q/3l0lDfDUbrDZD54+I7RQV9HfURshYBAWPVb4HIECd8Lxm3r/vCDmaZH
    n5jtDqmQ+OFvP/ZBGBeMXjCk
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-security-config
  namespace: eramba
data:
  security.conf: |
    ServerTokens Prod
    ServerSignature Off
    TraceEnable Off
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-ports-config
  namespace: eramba
data:
  ports.conf: |
    Listen 80
    Listen 8080
    Listen 443
    Listen 8443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-vhost-config
  namespace: eramba
data:
  vhost-ssl.conf: |
    <VirtualHost *:443 *:8443>
        DocumentRoot "/var/www/eramba"
        <Directory "/var/www/eramba">
            AllowOverride all
            Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLCertificateFile    /etc/ssl/certs/mycert.crt
        SSLCertificateKeyFile /etc/ssl/private/mycert.key
        LimitRequestLine 20000
    </VirtualHost>
