apiVersion: v1
kind: ConfigMap
metadata:
  name: eramba-config
  namespace: eramba
data:
  DB_HOST: "mysql"
  DB_DATABASE: "docker"
  DB_USERNAME: "docker"
  CACHE_URL: "Redis://?server=redis&port=6379&password=&timeout=3"
  USE_PROXY: "0"
  PROXY_HOST: ""
  PROXY_PORT: ""
  USE_PROXY_AUTH: "0"
  PROXY_AUTH_USER: ""
  PROXY_AUTH_PASS: ""
  PUBLIC_ADDRESS: "https://eramba.local"
  DOCKER_DEPLOYMENT: "1"
  LDAPTLS_REQCERT: "never"
