apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: eramba
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: mysql-init
        image: mysql:8.0.28-oracle
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          # Verificar se o diretório de dados está vazio
          if [ ! "$(ls -A /var/lib/mysql)" ]; then
            echo "Inicializando diretório de dados do MySQL..."
            # Copiar arquivos de inicialização se necessário
            chown -R mysql:mysql /var/lib/mysql
            chmod 755 /var/lib/mysql
          else
            echo "Diretório de dados já existe, pulando inicialização..."
          fi
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        securityContext:
          runAsUser: 0
      containers:
      - name: mysql
        image: mysql:8.0.28-oracle
        args: [ "--disable-log-bin" ]
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: eramba-config
              key: DB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: eramba-config
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eramba-secrets
              key: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eramba-secrets
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: mysql-init
        configMap:
          name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: eramba
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: eramba
data:
  custom.cnf: |
    [mysqld]
    innodb_buffer_pool_size = 256M
    max_connections = 200
    innodb_log_file_size = 64M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: eramba
data:
  grant.sh: |
    #!/bin/bash
    set -e

    # Aguardar MySQL estar disponível
    until mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1" > /dev/null 2>&1; do
      echo "Aguardando MySQL estar disponível..."
      sleep 2
    done

    # Configurar permissões
    mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';"
    mysql -u root -p$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"

    echo "Configuração do MySQL concluída!"
