apiVersion: v1
kind: Secret
metadata:
  name: eramba-secrets
  namespace: eramba
type: Opaque
data:
  # Base64 encoded passwords - substitua pelos seus valores reais
  # Para gerar: echo -n "sua_senha" | base64
  DB_PASSWORD: c2VuaGFfZGI= # senha_db
  MYSQL_ROOT_PASSWORD: c2VuaGFfZGI= # senha_db
